(()=>{if(document.getElementById('rig-launch'))return;
const css=document.createElement('style');css.textContent=`
#rig-launch{position:fixed;right:20px;bottom:20px;z-index:9998;border:0;border-radius:60px;background:#14283d;color:white;padding:12px 17px;box-shadow:0 8px 30px #0019;cursor:pointer;font:700 15px system-ui}
#rig-panel{position:fixed;right:20px;bottom:82px;z-index:9999;width:min(370px,calc(100vw - 24px));height:min(520px,calc(100dvh - 110px));display:none;flex-direction:column;background:#fff;border:1px solid #dae2eb;border-radius:18px;box-shadow:0 12px 50px #0014;overflow:hidden;font:14px system-ui;color:#14283d}
#rig-panel.open{display:flex}#rig-head{background:#14283d;color:#fff;padding:15px;display:flex;justify-content:space-between;align-items:center}#rig-head button{background:transparent;color:#fff;border:0;font-size:24px;cursor:pointer}
#rig-messages{padding:16px;flex:1;overflow:auto;display:flex;flex-direction:column;gap:12px} .rig-msg{padding:11px 13px;border-radius:13px;line-height:1.45;max-width:90%;white-space:pre-wrap}.rig-bot{background:#edf5fb;align-self:flex-start}.rig-user{background:#d9f3e6;align-self:flex-end}
#rig-actions{padding:10px;display:flex;flex-wrap:wrap;gap:7px}#rig-actions button{border:1px solid #c5d5e4;background:white;border-radius:18px;padding:7px 10px;cursor:pointer;color:#14283d}#rig-form{display:flex;padding:10px;gap:7px;border-top:1px solid #eee}#rig-input{flex:1;min-width:0;border:1px solid #c5d5e4;border-radius:10px;padding:10px}#rig-send{border:0;border-radius:10px;background:#f3ac24;padding:0 14px;cursor:pointer;font-weight:700}
@media(max-width:500px){#rig-panel{right:12px;bottom:75px}#rig-launch{right:12px;bottom:12px}}`;
document.head.appendChild(css);
const launch=document.createElement('button');launch.id='rig-launch';launch.textContent='👷🤖 Ask RIG';launch.setAttribute('aria-label','Open RIG WorkReady assistant');
const panel=document.createElement('section');panel.id='rig-panel';panel.setAttribute('aria-label','RIG contractor assistant');panel.innerHTML='<div id="rig-head"><div><strong>👷🤖 RIG · WorkReady</strong><div style="font-size:12px;opacity:.85">Your contractor readiness guide</div></div><button id="rig-close" aria-label="Close assistant">×</button></div><div id="rig-messages" aria-live="polite"></div><div id="rig-actions"></div><form id="rig-form"><input id="rig-input" autocomplete="off" maxlength="500" aria-label="Ask RIG" placeholder="Ask about contractor readiness…"><button id="rig-send">Send</button></form>';
document.body.append(launch,panel);
const messages=panel.querySelector('#rig-messages'),actions=panel.querySelector('#rig-actions'),input=panel.querySelector('#rig-input');
function say(t,who='bot'){const el=document.createElement('div');el.className='rig-msg rig-'+who;el.textContent=t;messages.append(el);messages.scrollTop=messages.scrollHeight}
function answer(q){const s=q.toLowerCase();if(/w.?9|tax form/.test(s))return 'A W-9 collects your taxpayer information. Sign in to your contractor dashboard to complete or upload the requested form. Never share your SSN or tax ID in this chat.';
if(/insurance|coi|coverage/.test(s))return 'Open your contractor dashboard and review the insurance requirements for each partner. Upload the requested certificate of insurance (COI) and check whether it has been reviewed. Coverage requirements vary by organization.';
if(/agreement|contract/.test(s))return 'Your partner may require a signed independent contractor agreement. Open your dashboard to review outstanding requirements and follow the provided signing workflow.';
if(/green|yellow|red|status|cleared|ready/.test(s))return 'WorkReady uses a traffic light system: 🟢 green means cleared under the current requirements; 🟡 yellow means something needs attention or may expire soon; 🔴 red means not cleared to work. Check your dashboard for your actual status; I cannot verify it from this chat.';
if(/upload|document|onboard|start/.test(s))return 'To get started: sign in, open your contractor checklist, complete your W-9 and agreement, upload any requested insurance or credentials, then watch for review updates. The organization sets its own requirements.';
if(/admin|organization|partner|invite/.test(s))return 'Organization admins can use their WorkReady dashboard to invite contractors, set requirements, and review readiness. This guide cannot access or change organization records.';
return 'I can guide you through onboarding, W-9s, agreements, insurance documents, and readiness statuses. For account-specific questions, check your dashboard or contact WorkReady support. I do not have access to your private records yet.'}
function ask(q){say(q,'user');say(answer(q))}
[['Get started','How do I start onboarding?'],['My status','What do green yellow red statuses mean?'],['W-9 help','How do I complete a W-9?'],['Insurance','What insurance documents do I need?']].forEach(([label,q])=>{const b=document.createElement('button');b.textContent=label;b.onclick=()=>ask(q);actions.append(b)});
say('Hey there! I’m RIG 👷🤖, your WorkReady contractor guide. I can help you navigate onboarding, documents, insurance, and compliance statuses. I’m in guide mode, so I can’t see your account or make changes yet.');
launch.onclick=()=>{panel.classList.toggle('open');if(panel.classList.contains('open'))input.focus()};panel.querySelector('#rig-close').onclick=()=>panel.classList.remove('open');panel.querySelector('#rig-form').onsubmit=e=>{e.preventDefault();const q=input.value.trim();if(q){input.value='';ask(q)}};
})();